using Rustaveli.Pdf.Documents;
using Rustaveli.Pdf.Fluent;
using Rustaveli.Pdf.Layout;
using Rustaveli.Pdf.Primitives;
using Rustaveli.Pdf.Skia;
using Rustaveli.Pdf.Text;

string output = args.Length > 0 ? args[0] : "gallery.pdf";

Document document = Document.Create(container =>
{
    container.Page(page =>
    {
        page.Size = PaperSizes.A4;
        page.Margin = Sides.All(40);
        page.DefaultTextStyle = TypeStyle.Default.FontFamilyOf("Arial").FontSizeOf(10);

        page.Header().Element(ComposeHeader);
        page.Footer().Element(ComposeFooter);

        // A faint diagonal marking behind everything, ignoring the page margins.
        page.Background().Centered().Middle().Text(text =>
            text.Span("SAMPLE").FontSize(96).FontColor(Palette.GreyLight));

        page.Content().InsetVertical(20).Column(column =>
        {
            column.Spacing(18);

            column.Item().Element(ComposeTypography);
            column.Item().Element(ComposeBoxes);
            column.Item().Element(ComposeLists);
            column.Item().Element(ComposeInvoiceTable);
            column.Item().Element(ComposeDirection);
            column.Item().Element(ComposeLinks);
        });
    });
});

document.Metadata.Title = "Rustaveli.Pdf Gallery";
document.Metadata.Author = "Rustaveli.Pdf";

document.GeneratePdf(output);

Console.WriteLine($"Wrote {output}");
return 0;

static void ComposeHeader(IFrame container) =>
    container.StrokeBottom(1).StrokeInk(Palette.GreyLight).InsetBottom(8).Row(row =>
    {
        row.RelativeItem().Text(text => text.Span("Rustaveli.Pdf").FontSize(16).Bold());

        // No AlignRight here: an Auto item is already snug against its content, and aligning inside one would
        // make it claim the whole row, leaving the relative item beside it with no width at all.
        row.AutoItem().Text(text => text.Span("Feature gallery").FontColor(Palette.GreyDark));
    });

static void ComposeFooter(IFrame container) =>
    container.InsetTop(8).StrokeTop(1).StrokeInk(Palette.GreyLight).InsetTop(6).Row(row =>
    {
        row.RelativeItem().Text(text =>
            text.Span("Generated by Rustaveli.Pdf").FontColor(Palette.Grey).FontSize(8));

        row.AutoItem().Text(text =>
        {
            text.DefaultType(style => style.ColorOf(Palette.Grey).FontSizeOf(8));
            text.Span("Page ");
            text.CurrentPageNumber().Bold();
            text.Span(" of ");
            text.TotalPages().Bold();
        });
    });

static void ComposeSection(IFrame container, string title, Action<IFrame> body) =>
    container.Column(column =>
    {
        column.Spacing(6);
        column.Item().Text(text => text.Span(title).FontSize(13).Bold().FontColor(Palette.Indigo));
        column.Item().Rule(0.5f, Palette.GreyLight);
        column.Item().Element(body);
    });

static void ComposeTypography(IFrame container) =>
    ComposeSection(container, "Typography", body => body.Column(column =>
    {
        column.Spacing(3);

        column.Item().Text(text =>
        {
            text.Span("Styles compose: ");
            text.Span("bold").Bold();
            text.Span(", ");
            text.Span("italic").Italic();
            text.Span(", ");
            text.Span("underlined").Underline();
            text.Span(", ");
            text.Span("struck through").Strikethrough();
            text.Span(", ");
            text.Span("highlighted").BackgroundColor(Palette.Yellow);
            text.Span(", and coloured").FontColor(Palette.Red);
            text.Span(".");
        });

        column.Item().Text(text =>
        {
            text.Span("Chemical formulae such as H");
            text.Span("2").Subscript();
            text.Span("O and exponents such as e");
            text.Span("iπ").Superscript();
            text.Span(" sit on shifted baselines.");
        });

        column.Item().Text(text =>
        {
            text.Span("Long paragraphs wrap at the available width and flow onto the next page when they run "
                + "out of room. The engine measures every line before drawing anything, so a break never "
                + "leaves content half-drawn.");
        });

        column.Item().Text(text =>
        {
            text.Centered();
            text.Span("Centred").FontColor(Palette.Teal);
        });

        column.Item().Text(text =>
        {
            text.FlushRight();
            text.Span("Right aligned").FontColor(Palette.Teal);
        });
    }));

static void ComposeBoxes(IFrame container) =>
    ComposeSection(container, "Boxes, borders and alignment", body => body.Row(row =>
    {
        row.Spacing(10);

        row.RelativeItem().Stroke(1).StrokeInk(Palette.Grey).Inset(8).Column(column =>
        {
            column.Spacing(4);
            column.Item().Text("Bordered box");
            column.Item().Fill(Palette.GreyLight).Inset(6).Text("With a filled panel inside");
        });

        row.RelativeItem().Height(70).Fill(Palette.Indigo).Inset(8).Centered().Middle()
            .Text(text => text.Span("Centred on both axes").FontColor(Ink.White));

        row.ConstantItem(70).Height(70).Proportion(1f).Placeholder(Palette.GreyLight);
    }));

static void ComposeLists(IFrame container) =>
    ComposeSection(container, "Lists, rounded containers and scaling", body => body.Row(row =>
    {
        row.Spacing(14);

        row.RelativeItem().List(list =>
        {
            list.Spacing(2);
            list.Item().Text("A bulleted item");
            list.Item().Text("Another, long enough that it wraps and the continuation lines stay clear of the marker gutter");
            list.Item().Text("A third");
        });

        row.RelativeItem().List(list =>
        {
            list.Ordered();
            list.Spacing(2);
            list.MarkerStyle(style => style.Bold().ColorOf(Palette.Indigo));
            list.Item().Text("Numbered items");
            list.Item().Text("keep counting");
            list.Item().Text("across page breaks");
        });

        row.RelativeItem().Column(column =>
        {
            column.Spacing(6);

            column.Item()
                .Fill(Palette.Amber).RoundCorners(8)
                .Inset(8)
                .Text("Rounded fill");

            column.Item()
                .Stroke(1).StrokeInk(Palette.Teal).RoundCorners(8)
                .Inset(8)
                .Text("Rounded outline");

            column.Item().ShrinkToFit()
                .Text("This sentence is scaled down until it fits the column it was given.");
        });
    }));

static void ComposeInvoiceTable(IFrame container) =>
    ComposeSection(container, "Tables", body => body.Table(table =>
    {
        table.ColumnsDefinition(columns =>
        {
            columns.ConstantColumn(70);
            columns.RelativeColumn();
            columns.ConstantColumn(50);
            columns.ConstantColumn(70);
        });

        table.Header(header =>
        {
            foreach (string? heading in new[] { "Code", "Description", "Qty", "Amount" })
            {
                header.Cell()
                    .Fill(Palette.Indigo)
                    .Inset(5)
                    .Text(text => text.Span(heading).Bold().FontColor(Ink.White));
            }
        });

        for (int index = 1; index <= 18; index++)
        {
            Ink shade = index % 2 == 0 ? Ink.White : Palette.GreyLight;

            table.Cell().Fill(shade).Inset(5).Text($"SKU-{index:D3}");
            table.Cell().Fill(shade).Inset(5).Text($"Line item number {index}");
            table.Cell().Fill(shade).Inset(5).FlushRight().Text($"{index}");
            table.Cell().Fill(shade).Inset(5).FlushRight().Text($"{index * 12.5m:F2}");
        }

        // A footer band, repeated on every page the table spans.
        table.Footer(footer =>
        {
            footer.Cell().ColumnSpan(3).Inset(5).FlushRight()
                .Text(text => text.Span("Total").Bold());

            footer.Cell().Inset(5).FlushRight()
                .Text(text => text.Span($"{Enumerable.Range(1, 18).Sum(i => i * 12.5m):F2}").Bold());
        });
    }));

static void ComposeDirection(IFrame container) =>
    ComposeSection(container, "Content direction", body => body.Column(column =>
    {
        column.Spacing(6);

        column.Item().Row(row =>
        {
            row.Spacing(6);
            row.ConstantItem(60).Fill(Palette.Teal).Inset(4)
                .Text(text => text.Span("first").FontColor(Ink.White));
            row.ConstantItem(60).Fill(Palette.Cyan).Inset(4).Text("second");
            row.RelativeItem().Text(text =>
                text.Span("left to right").FontColor(Palette.Grey));
        });

        column.Item().RightToLeft().Row(row =>
        {
            row.Spacing(6);
            row.ConstantItem(60).Fill(Palette.Teal).Inset(4)
                .Text(text => text.Span("first").FontColor(Ink.White));
            row.ConstantItem(60).Fill(Palette.Cyan).Inset(4).Text("second");
            row.RelativeItem().Text(text =>
                text.Span("right to left").FontColor(Palette.Grey));
        });
    }));

static void ComposeLinks(IFrame container) =>
    ComposeSection(container, "Links and sections", body => body.Column(column =>
    {
        column.Spacing(4);

        column.Item().Anchor("gallery-end").Text("This paragraph is a named destination.");

        column.Item().Text(text =>
        {
            text.Span("An external ");
            text.Link("hyperlink", "https://example.com").FontColor(Palette.Blue).Underline();
            text.Span(" and an internal ");
            text.CrossReference("jump", "gallery-end").FontColor(Palette.Blue).Underline();
            text.Span(" to the destination above.");
        });
    }));
