using Rustaveli.Pdf.Documents;
using Rustaveli.Pdf.Fluent;
using Rustaveli.Pdf.Layout;
using Rustaveli.Pdf.Primitives;
using Rustaveli.Pdf.Skia;
using Rustaveli.Pdf.Text;

string output = args.Length > 0 ? args[0] : "gallery.pdf";

Document document = Document.Create(container =>
{
    container.Page(page =>
    {
        page.Size = PageSizes.A4;
        page.Margin = Edges.All(40);
        page.DefaultTextStyle = TextStyle.Default.FontFamilyOf("Arial").FontSizeOf(10);

        page.Header().Element(ComposeHeader);
        page.Footer().Element(ComposeFooter);

        // A faint diagonal marking behind everything, ignoring the page margins.
        page.Background().AlignCenter().AlignMiddle().Text(text =>
            text.Span("SAMPLE").FontSize(96).FontColor(Colors.Grey.Lighten3));

        page.Content().PaddingVertical(20).Column(column =>
        {
            column.Spacing(18);

            column.Item().Element(ComposeTypography);
            column.Item().Element(ComposeBoxes);
            column.Item().Element(ComposeLists);
            column.Item().Element(ComposeInvoiceTable);
            column.Item().Element(ComposeDirection);
            column.Item().Element(ComposeLinks);
        });
    });
});

document.Metadata.Title = "Rustaveli.Pdf Gallery";
document.Metadata.Author = "Rustaveli.Pdf";

document.GeneratePdf(output);

Console.WriteLine($"Wrote {output}");
return 0;

static void ComposeHeader(IContainer container) =>
    container.BorderBottom(1).BorderColor(Colors.Grey.Lighten3).PaddingBottom(8).Row(row =>
    {
        row.RelativeItem().Text(text => text.Span("Rustaveli.Pdf").FontSize(16).Bold());

        // No AlignRight here: an Auto item is already snug against its content, and aligning inside one would
        // make it claim the whole row, leaving the relative item beside it with no width at all.
        row.AutoItem().Text(text => text.Span("Feature gallery").FontColor(Colors.Grey.Darken2));
    });

static void ComposeFooter(IContainer container) =>
    container.PaddingTop(8).BorderTop(1).BorderColor(Colors.Grey.Lighten3).PaddingTop(6).Row(row =>
    {
        row.RelativeItem().Text(text =>
            text.Span("Generated by Rustaveli.Pdf").FontColor(Colors.Grey).FontSize(8));

        row.AutoItem().Text(text =>
        {
            text.DefaultTextStyle(style => style.ColorOf(Colors.Grey).FontSizeOf(8));
            text.Span("Page ");
            text.CurrentPageNumber().Bold();
            text.Span(" of ");
            text.TotalPages().Bold();
        });
    });

static void ComposeSection(IContainer container, string title, Action<IContainer> body) =>
    container.Column(column =>
    {
        column.Spacing(6);
        column.Item().Text(text => text.Span(title).FontSize(13).Bold().FontColor(Colors.Indigo));
        column.Item().LineHorizontal(0.5f, Colors.Grey.Lighten3);
        column.Item().Element(body);
    });

static void ComposeTypography(IContainer container) =>
    ComposeSection(container, "Typography", body => body.Column(column =>
    {
        column.Spacing(3);

        column.Item().Text(text =>
        {
            text.Span("Styles compose: ");
            text.Span("bold").Bold();
            text.Span(", ");
            text.Span("italic").Italic();
            text.Span(", ");
            text.Span("underlined").Underline();
            text.Span(", ");
            text.Span("struck through").Strikethrough();
            text.Span(", ");
            text.Span("highlighted").BackgroundColor(Colors.Yellow);
            text.Span(", and coloured").FontColor(Colors.Red);
            text.Span(".");
        });

        column.Item().Text(text =>
        {
            text.Span("Chemical formulae such as H");
            text.Span("2").Subscript();
            text.Span("O and exponents such as e");
            text.Span("iπ").Superscript();
            text.Span(" sit on shifted baselines.");
        });

        column.Item().Text(text =>
        {
            text.Span("Long paragraphs wrap at the available width and flow onto the next page when they run "
                + "out of room. The engine measures every line before drawing anything, so a break never "
                + "leaves content half-drawn.");
        });

        column.Item().Text(text =>
        {
            text.AlignCenter();
            text.Span("Centred").FontColor(Colors.Teal);
        });

        column.Item().Text(text =>
        {
            text.AlignRight();
            text.Span("Right aligned").FontColor(Colors.Teal);
        });
    }));

static void ComposeBoxes(IContainer container) =>
    ComposeSection(container, "Boxes, borders and alignment", body => body.Row(row =>
    {
        row.Spacing(10);

        row.RelativeItem().Border(1).BorderColor(Colors.Grey).Padding(8).Column(column =>
        {
            column.Spacing(4);
            column.Item().Text("Bordered box");
            column.Item().Background(Colors.Grey.Lighten3).Padding(6).Text("With a filled panel inside");
        });

        row.RelativeItem().Height(70).Background(Colors.Indigo).Padding(8).AlignCenter().AlignMiddle()
            .Text(text => text.Span("Centred on both axes").FontColor(Colors.White));

        row.ConstantItem(70).Height(70).AspectRatio(1f).Placeholder(Colors.Grey.Lighten3);
    }));

static void ComposeLists(IContainer container) =>
    ComposeSection(container, "Lists, rounded containers and scaling", body => body.Row(row =>
    {
        row.Spacing(14);

        row.RelativeItem().List(list =>
        {
            list.Spacing(2);
            list.Item().Text("A bulleted item");
            list.Item().Text("Another, long enough that it wraps and the continuation lines stay clear of the marker gutter");
            list.Item().Text("A third");
        });

        row.RelativeItem().List(list =>
        {
            list.Ordered();
            list.Spacing(2);
            list.MarkerStyle(style => style.Bold().ColorOf(Colors.Indigo));
            list.Item().Text("Numbered items");
            list.Item().Text("keep counting");
            list.Item().Text("across page breaks");
        });

        row.RelativeItem().Column(column =>
        {
            column.Spacing(6);

            column.Item()
                .Background(Colors.Amber.Lighten4).CornerRadius(8)
                .Padding(8)
                .Text("Rounded fill");

            column.Item()
                .Border(1).BorderColor(Colors.Teal).CornerRadius(8)
                .Padding(8)
                .Text("Rounded outline");

            column.Item().ScaleToFit()
                .Text("This sentence is scaled down until it fits the column it was given.");
        });
    }));

static void ComposeInvoiceTable(IContainer container) =>
    ComposeSection(container, "Tables", body => body.Table(table =>
    {
        table.ColumnsDefinition(columns =>
        {
            columns.ConstantColumn(70);
            columns.RelativeColumn();
            columns.ConstantColumn(50);
            columns.ConstantColumn(70);
        });

        table.Header(header =>
        {
            foreach (string? heading in new[] { "Code", "Description", "Qty", "Amount" })
            {
                header.Cell()
                    .Background(Colors.Indigo)
                    .Padding(5)
                    .Text(text => text.Span(heading).Bold().FontColor(Colors.White));
            }
        });

        for (int index = 1; index <= 18; index++)
        {
            Color shade = index % 2 == 0 ? Colors.White : Colors.Grey.Lighten3;

            table.Cell().Background(shade).Padding(5).Text($"SKU-{index:D3}");
            table.Cell().Background(shade).Padding(5).Text($"Line item number {index}");
            table.Cell().Background(shade).Padding(5).AlignRight().Text($"{index}");
            table.Cell().Background(shade).Padding(5).AlignRight().Text($"{index * 12.5m:F2}");
        }

        // A footer band, repeated on every page the table spans.
        table.Footer(footer =>
        {
            footer.Cell().ColumnSpan(3).Padding(5).AlignRight()
                .Text(text => text.Span("Total").Bold());

            footer.Cell().Padding(5).AlignRight()
                .Text(text => text.Span($"{Enumerable.Range(1, 18).Sum(i => i * 12.5m):F2}").Bold());
        });
    }));

static void ComposeDirection(IContainer container) =>
    ComposeSection(container, "Content direction", body => body.Column(column =>
    {
        column.Spacing(6);

        column.Item().Row(row =>
        {
            row.Spacing(6);
            row.ConstantItem(60).Background(Colors.Teal).Padding(4)
                .Text(text => text.Span("first").FontColor(Colors.White));
            row.ConstantItem(60).Background(Colors.Cyan).Padding(4).Text("second");
            row.RelativeItem().Text(text =>
                text.Span("left to right").FontColor(Colors.Grey));
        });

        column.Item().RightToLeft().Row(row =>
        {
            row.Spacing(6);
            row.ConstantItem(60).Background(Colors.Teal).Padding(4)
                .Text(text => text.Span("first").FontColor(Colors.White));
            row.ConstantItem(60).Background(Colors.Cyan).Padding(4).Text("second");
            row.RelativeItem().Text(text =>
                text.Span("right to left").FontColor(Colors.Grey));
        });
    }));

static void ComposeLinks(IContainer container) =>
    ComposeSection(container, "Links and sections", body => body.Column(column =>
    {
        column.Spacing(4);

        column.Item().Section("gallery-end").Text("This paragraph is a named destination.");

        column.Item().Text(text =>
        {
            text.Span("An external ");
            text.Hyperlink("hyperlink", "https://example.com").FontColor(Colors.Blue).Underline();
            text.Span(" and an internal ");
            text.SectionLink("jump", "gallery-end").FontColor(Colors.Blue).Underline();
            text.Span(" to the destination above.");
        });
    }));
