// Builds the character property tables the bidirectional algorithm reads, from the Unicode Character Database files
// committed under tests/assets/unicode.
//
//     dotnet run eng/unicode-bidi.cs
//
// Writes src/Rustaveli.Pdf/Text/Bidi/BidiCharacterTables.cs. Run it again after replacing the data files with those of
// a newer Unicode version; the output is committed, so a build never needs the data files or this script.
//
// Bidi_Class covers every code point, so it is stored as a three-stage table: the code point's high bits pick a block
// of indices, its middle bits pick a block of classes, its low bits pick the class. Identical blocks are stored once,
// which is what makes it small: most of the code space is unassigned and shares a handful of blocks. The stage sizes
// are chosen here by trying them all, keeping every index within a byte.

using System.Globalization;
using System.Text;

string root = RepositoryRoot();
string data = Path.Combine(root, "tests", "assets", "unicode");
string output = Path.Combine(root, "src", "Rustaveli.Pdf", "Text", "Bidi", "BidiCharacterTables.cs");

// The order of BidiClass, whose values the tables store.
string[] classNames =
    ["L", "R", "AL", "EN", "ES", "ET", "AN", "CS", "NSM", "BN", "B", "S", "WS", "ON",
     "LRE", "LRO", "RLE", "RLO", "PDF", "LRI", "RLI", "FSI", "PDI"];

// The @missing lines, which give the class of code points the data lines do not list, use the long value aliases.
Dictionary<string, string> longNames = new Dictionary<string, string>
{
    ["Left_To_Right"] = "L", ["Right_To_Left"] = "R", ["Arabic_Letter"] = "AL", ["European_Number"] = "EN",
    ["European_Separator"] = "ES", ["European_Terminator"] = "ET", ["Arabic_Number"] = "AN",
    ["Common_Separator"] = "CS", ["Nonspacing_Mark"] = "NSM", ["Boundary_Neutral"] = "BN",
    ["Paragraph_Separator"] = "B", ["Segment_Separator"] = "S", ["White_Space"] = "WS", ["Other_Neutral"] = "ON",
    ["Left_To_Right_Embedding"] = "LRE", ["Left_To_Right_Override"] = "LRO", ["Right_To_Left_Embedding"] = "RLE",
    ["Right_To_Left_Override"] = "RLO", ["Pop_Directional_Format"] = "PDF", ["Left_To_Right_Isolate"] = "LRI",
    ["Right_To_Left_Isolate"] = "RLI", ["First_Strong_Isolate"] = "FSI", ["Pop_Directional_Isolate"] = "PDI",
};

const int CodeSpace = 0x110000;

string version = Version("DerivedBidiClass.txt");
foreach (string file in new[] { "BidiBrackets.txt", "BidiMirroring.txt" })
{
    if (Version(file) != version)
        throw new InvalidOperationException($"{file} is not from Unicode {version}.");
}

byte[] classes = new byte[CodeSpace];

// Defaults first, in file order, since later @missing lines refine the first, which covers the whole code space.
foreach (string line in File.ReadLines(Path.Combine(data, "DerivedBidiClass.txt")))
{
    const string Missing = "# @missing:";
    if (!line.StartsWith(Missing, StringComparison.Ordinal))
        continue;

    string[] fields = line.Substring(Missing.Length).Split(';');
    Fill(classes, fields[0], ClassValue(longNames[fields[1].Trim()]));
}

foreach (string[] fields in DataLines("DerivedBidiClass.txt"))
    Fill(classes, fields[0], ClassValue(fields[1]));

(int indexShift, int blockShift, byte[] stage1, byte[] stage2, byte[] stage3) = SmallestTrie(classes);

for (int codepoint = 0; codepoint < CodeSpace; codepoint++)
{
    int block = stage1[codepoint >> (indexShift + blockShift)];
    int entries = stage2[(block << indexShift) + ((codepoint >> blockShift) & ((1 << indexShift) - 1))];
    if (stage3[(entries << blockShift) + (codepoint & ((1 << blockShift) - 1))] != classes[codepoint])
        throw new InvalidOperationException($"The table disagrees with the data at U+{codepoint:X4}.");
}

List<(int Codepoint, int Mirror)> mirrors = DataLines("BidiMirroring.txt")
    .Select(fields => (Hex(fields[0]), Hex(fields[1])))
    .OrderBy(entry => entry.Item1)
    .ToList();

List<(int Codepoint, int Pair, int Type)> brackets = DataLines("BidiBrackets.txt")
    .Select(fields => (Hex(fields[0]), Hex(fields[1]), fields[2].Trim() == "o" ? 1 : 2))
    .OrderBy(entry => entry.Item1)
    .ToList();

// Both lists are searched as big-endian 16-bit values; a supplementary entry would need a wider record.
if (mirrors.Any(entry => entry.Codepoint > 0xFFFF || entry.Mirror > 0xFFFF) ||
    brackets.Any(entry => entry.Codepoint > 0xFFFF || entry.Pair > 0xFFFF))
{
    throw new InvalidOperationException("Mirrored and bracket characters are expected in the Basic Multilingual Plane.");
}

StringBuilder source = new StringBuilder();
source.Append($$"""
    namespace Rustaveli.Pdf.Text.Bidi;

    /// <summary>
    /// The bidirectional character properties of Unicode {{version}}: Bidi_Class, Bidi_Paired_Bracket,
    /// Bidi_Paired_Bracket_Type and Bidi_Mirroring_Glyph.
    /// </summary>
    /// <remarks>
    /// Generated by eng/unicode-bidi.cs from DerivedBidiClass.txt, BidiBrackets.txt and BidiMirroring.txt; change the
    /// script and run it again rather than editing this file. The data is derived from the Unicode Character Database,
    /// copyright Unicode, Inc., under the Unicode License v3 (tests/assets/unicode/README.md). The tables are byte spans
    /// over constant data, which the compiler places in the assembly image: reading them allocates nothing on either
    /// target.
    /// </remarks>
    internal static class BidiCharacterTables
    {
        public const string UnicodeVersion = "{{version}}";

        /// <summary>The low bits of a code point, which select its class within a block of <see cref="ClassStage3"/>.</summary>
        public const int ClassStage3Bits = {{blockShift}};

        /// <summary>The middle bits of a code point, which select its block within a run of <see cref="ClassStage2"/>.</summary>
        public const int ClassStage2Bits = {{indexShift}};

        /// <summary>Mirrored pairs as big-endian 16-bit values, code point then mirror, sorted by code point.</summary>
        public const int MirrorRecordSize = 4;

        /// <summary>Brackets as big-endian 16-bit code point and pair, then 1 for opening or 2 for closing.</summary>
        public const int BracketRecordSize = 5;


    """);

AppendTable(source, "ClassStage1", "Indexed by the high bits of a code point: the run of stage two to read.", stage1);
AppendTable(source, "ClassStage2", "Runs of block numbers: the block of stage three each group of code points reads.", stage2);
AppendTable(source, "ClassStage3", "Blocks of classes, as BidiClass values.", stage3);
AppendTable(
    source,
    "Mirrors",
    "Bidi_Mirroring_Glyph.",
    mirrors.SelectMany(entry => new[] { entry.Codepoint >> 8, entry.Codepoint & 0xFF, entry.Mirror >> 8, entry.Mirror & 0xFF })
        .Select(value => (byte)value)
        .ToArray());
AppendTable(
    source,
    "Brackets",
    "Bidi_Paired_Bracket and Bidi_Paired_Bracket_Type.",
    brackets.SelectMany(entry => new[] { entry.Codepoint >> 8, entry.Codepoint & 0xFF, entry.Pair >> 8, entry.Pair & 0xFF, entry.Type })
        .Select(value => (byte)value)
        .ToArray(),
    last: true);

source.Append("}\n");
Directory.CreateDirectory(Path.GetDirectoryName(output)!);
File.WriteAllText(output, source.ToString().Replace("\r\n", "\n"), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

Console.WriteLine($"Unicode {version}: {stage1.Length + stage2.Length + stage3.Length} bytes of classes " +
                  $"(stages {stage1.Length}, {stage2.Length}, {stage3.Length}), {mirrors.Count} mirrors, " +
                  $"{brackets.Count} brackets");
Console.WriteLine($"wrote {output}");
return 0;

byte ClassValue(string name)
{
    int value = Array.IndexOf(classNames, name.Trim());
    if (value < 0)
        throw new InvalidOperationException($"Unknown Bidi_Class value '{name}'.");

    return (byte)value;
}

string Version(string file)
{
    // The first line names the file and its version: "# DerivedBidiClass-16.0.0.txt".
    string first = File.ReadLines(Path.Combine(data, file)).First();
    int dash = first.LastIndexOf('-');
    return first.Substring(dash + 1, first.Length - dash - 1 - ".txt".Length);
}

IEnumerable<string[]> DataLines(string file)
{
    foreach (string line in File.ReadLines(Path.Combine(data, file)))
    {
        int comment = line.IndexOf('#');
        string content = (comment < 0 ? line : line.Substring(0, comment)).Trim();
        if (content.Length > 0)
            yield return content.Split(';');
    }
}

static int Hex(string value) => int.Parse(value.Trim(), NumberStyles.HexNumber, CultureInfo.InvariantCulture);

static void Fill(byte[] table, string range, byte value)
{
    string[] ends = range.Trim().Split("..");
    int first = Hex(ends[0]);
    int last = ends.Length == 2 ? Hex(ends[1]) : first;
    table.AsSpan(first, last - first + 1).Fill(value);
}

static (int IndexShift, int BlockShift, byte[] Stage1, byte[] Stage2, byte[] Stage3) SmallestTrie(byte[] values)
{
    (int, int, byte[], byte[], byte[])? best = null;
    int bestSize = int.MaxValue;

    for (int blockShift = 1; blockShift <= 8; blockShift++)
    {
        for (int indexShift = 1; indexShift <= 8; indexShift++)
        {
            if (Deduplicate(values, 1 << blockShift) is not (byte[] blockIndex, byte[] blocks))
                continue;

            if (Deduplicate(blockIndex, 1 << indexShift) is not (byte[] runIndex, byte[] runs))
                continue;

            int size = runIndex.Length + runs.Length + blocks.Length;
            if (size < bestSize)
            {
                bestSize = size;
                best = (indexShift, blockShift, runIndex, runs, blocks);
            }
        }
    }

    return best ?? throw new InvalidOperationException("No stage sizes keep the indices within a byte.");
}

// Splits the values into blocks of the given size and stores each distinct block once: the index of each block's
// stored copy, and the stored blocks. Null when there are more distinct blocks than a byte can index.
static (byte[] Index, byte[] Blocks)? Deduplicate(byte[] values, int blockSize)
{
    Dictionary<string, int> seen = new Dictionary<string, int>();
    List<byte> blocks = new List<byte>();
    byte[] index = new byte[values.Length / blockSize];

    for (int block = 0; block < index.Length; block++)
    {
        ArraySegment<byte> content = new ArraySegment<byte>(values, block * blockSize, blockSize);
        string key = Convert.ToBase64String(content.Array!, content.Offset, content.Count);

        if (!seen.TryGetValue(key, out int stored))
        {
            stored = seen.Count;
            if (stored > byte.MaxValue)
                return null;

            seen.Add(key, stored);
            blocks.AddRange(content);
        }

        index[block] = (byte)stored;
    }

    return (index, blocks.ToArray());
}

static void AppendTable(StringBuilder source, string name, string summary, byte[] values, bool last = false)
{
    source.Append($"    /// <summary>{summary}</summary>\n");
    source.Append($"    public static ReadOnlySpan<byte> {name} => new byte[]\n");
    source.Append("    {\n");

    StringBuilder line = new StringBuilder();
    foreach (byte value in values)
    {
        string item = value.ToString(CultureInfo.InvariantCulture) + ",";
        if (line.Length > 0 && 8 + line.Length + 1 + item.Length > 120)
        {
            source.Append("        ").Append(line).Append('\n');
            line.Clear();
        }

        if (line.Length > 0)
            line.Append(' ');

        line.Append(item);
    }

    if (line.Length > 0)
        source.Append("        ").Append(line).Append('\n');

    source.Append("    };\n");
    if (!last)
        source.Append('\n');
}

// Found by walking up from the working directory, not from this script's location: a file-based app's build output
// is cached and can be shared between checkouts, so a path captured at compile time may name a different one.
static string RepositoryRoot()
{
    for (DirectoryInfo? directory = new DirectoryInfo(Environment.CurrentDirectory); directory != null; directory = directory.Parent)
    {
        if (File.Exists(Path.Combine(directory.FullName, "Rustaveli.Pdf.slnx")))
            return directory.FullName;
    }

    throw new InvalidOperationException("Run this from inside the Rustaveli.Pdf repository.");
}
